# Generated by Django 4.1.7 on 2023-03-18 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='color',
            table='Color',
        ),
    ]
