# Generated by Django 4.1.7 on 2023-03-18 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_color_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='Department',
        ),
        migrations.AlterField(
            model_name='employees',
            name='favorite_color',
            field=models.ForeignKey(db_column='favorite_color', default=2, on_delete=django.db.models.deletion.CASCADE, to='employees.color'),
        ),
        migrations.AlterModelTable(
            name='department',
            table='Department',
        ),
        migrations.AlterModelTable(
            name='employees',
            table='Employees',
        ),
        migrations.AddField(
            model_name='employees',
            name='department',
            field=models.ForeignKey(db_column='department', default=None, on_delete=django.db.models.deletion.CASCADE, to='employees.department'),
        ),
    ]
